// <auto-generated />
using System;
using GestionDeMisiones.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionDeMisiones.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251022011952_CreacionDeHechiceroEncargadoFix")]
    partial class CreacionDeHechiceroEncargadoFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionDeMisiones.Models.Hechicero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("Experiencia")
                        .HasColumnType("int");

                    b.Property<int>("Grado")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TecnicaPrincipalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TecnicaPrincipalId");

                    b.ToTable("Hechiceros");
                });

            modelBuilder.Entity("GestionDeMisiones.Models.HechiceroEncargado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HechiceroId")
                        .HasColumnType("int");

                    b.Property<int>("MisionId")
                        .HasColumnType("int");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HechiceroId");

                    b.HasIndex("MisionId");

                    b.HasIndex("SolicitudId");

                    b.ToTable("HechiceroEncargado");
                });

            modelBuilder.Entity("GestionDeMisiones.Models.Maldicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoActual")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaYHoraDeAparicion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Grado")
                        .HasColumnType("int");

                    b.Property<int>("NivelPeligro")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("UbicacionDeAparicionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UbicacionDeAparicionId");

                    b.ToTable("Maldiciones");
                });

            modelBuilder.Entity("GestionDeMisiones.Models.Mision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DannosColaterales")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("EventosOcurridos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaYHoraDeFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaYHoraDeInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("NivelUrgencia")
                        .HasColumnType("int");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Misiones");
                });

            modelBuilder.Entity("GestionDeMisiones.Models.PersonalDeApoyo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonalDeApoyo");
                });

            modelBuilder.Entity("GestionDeMisiones.Models.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoRecurso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("GestionDeMisiones.Models.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("MaldicionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaldicionId");

                    b.ToTable("Solicitud");
                });

            modelBuilder.Entity("GestionDeMisiones.Models.TecnicaMaldita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CondicionesDeUso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EfectividadProm")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TecnicasMalditas");
                });

            modelBuilder.Entity("GestionDeMisiones.Models.Traslado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DestinoId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrigenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinoId");

                    b.HasIndex("OrigenId");

                    b.ToTable("Traslados");
                });

            modelBuilder.Entity("GestionDeMisiones.Models.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("GestionDeMisiones.Models.UsoDeRecurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MisionId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecursoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MisionId");

                    b.HasIndex("RecursoId");

                    b.ToTable("UsosDeRecurso");
                });

            modelBuilder.Entity("GestionDeMisiones.Models.Hechicero", b =>
                {
                    b.HasOne("GestionDeMisiones.Models.TecnicaMaldita", "TecnicaPrincipal")
                        .WithMany()
                        .HasForeignKey("TecnicaPrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TecnicaPrincipal");
                });

            modelBuilder.Entity("GestionDeMisiones.Models.HechiceroEncargado", b =>
                {
                    b.HasOne("GestionDeMisiones.Models.Hechicero", "Hechicero")
                        .WithMany()
                        .HasForeignKey("HechiceroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionDeMisiones.Models.Mision", "Mision")
                        .WithMany()
                        .HasForeignKey("MisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionDeMisiones.Models.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hechicero");

                    b.Navigation("Mision");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("GestionDeMisiones.Models.Maldicion", b =>
                {
                    b.HasOne("GestionDeMisiones.Models.Ubicacion", "UbicacionDeAparicion")
                        .WithMany()
                        .HasForeignKey("UbicacionDeAparicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UbicacionDeAparicion");
                });

            modelBuilder.Entity("GestionDeMisiones.Models.Mision", b =>
                {
                    b.HasOne("GestionDeMisiones.Models.Ubicacion", "Ubicacion")
                        .WithMany("Misiones")
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("GestionDeMisiones.Models.Solicitud", b =>
                {
                    b.HasOne("GestionDeMisiones.Models.Maldicion", "Maldicion")
                        .WithMany()
                        .HasForeignKey("MaldicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maldicion");
                });

            modelBuilder.Entity("GestionDeMisiones.Models.Traslado", b =>
                {
                    b.HasOne("GestionDeMisiones.Models.Ubicacion", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionDeMisiones.Models.Ubicacion", "Origen")
                        .WithMany()
                        .HasForeignKey("OrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destino");

                    b.Navigation("Origen");
                });

            modelBuilder.Entity("GestionDeMisiones.Models.UsoDeRecurso", b =>
                {
                    b.HasOne("GestionDeMisiones.Models.Mision", "Mision")
                        .WithMany("UsosDeRecurso")
                        .HasForeignKey("MisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionDeMisiones.Models.Recurso", "Recurso")
                        .WithMany("UsosDeRecurso")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mision");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("GestionDeMisiones.Models.Mision", b =>
                {
                    b.Navigation("UsosDeRecurso");
                });

            modelBuilder.Entity("GestionDeMisiones.Models.Recurso", b =>
                {
                    b.Navigation("UsosDeRecurso");
                });

            modelBuilder.Entity("GestionDeMisiones.Models.Ubicacion", b =>
                {
                    b.Navigation("Misiones");
                });
#pragma warning restore 612, 618
        }
    }
}
